name: Update prebuilt blobs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  update:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - module: "Galaxy A52 (a52qnsxx)"
            path: "prebuilts/samsung/a52qnsxx"
          - module: "Galaxy A52s 5G (a52sxqxx)"
            path: "prebuilts/samsung/a52sxqxx"
          - module: "Galaxy A73 5G (a73xqxx)"
            path: "prebuilts/samsung/a73xqxx"
          - module: "Galaxy Z Fold5 (b5qxxx)"
            path: "prebuilts/samsung/b5qxxx"
          - module: "Galaxy S23 (dm1qkdiw)"
            path: "prebuilts/samsung/dm1qkdiw"
          - module: "Galaxy S23 Ultra (dm3qxxx)"
            path: "prebuilts/samsung/dm3qxxx"
          - module: "Galaxy S24 (e1qzcx)"
            path: "prebuilts/samsung/e1qzcx"
          - module: "Galaxy Tab S9 (gts9xxx)"
            path: "prebuilts/samsung/gts9xxx"
          - module: "Galaxy S22 (r0qxxx)"
            path: "prebuilts/samsung/r0qxxx"
          - module: "Galaxy S21 FE 5G (r9qxxx)"
            path: "prebuilts/samsung/r9qxxx"
          - module: "Galaxy S23 FE (r11sxxx)"
            path: "prebuilts/samsung/r11sxxx"
          - module: "(dm1q) China firmware blobs"
            path: "target/dm1q/patches/china"
          - module: "(dm2q) China firmware blobs"
            path: "target/dm2q/patches/china"
          - module: "(dm3q) China firmware blobs"
            path: "target/dm3q/patches/china"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Free disk space (1/3)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Free disk space (2/3)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Free disk space (3/3)
        uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: 'compiler_cmake'

      - name: Set up build environment
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            attr ccache clang ffmpeg golang \
            libbrotli-dev libgtest-dev libprotobuf-dev libunwind-dev libpcre2-dev \
            libzstd-dev linux-modules-extra-$(uname -r) lld protobuf-compiler webp
          sudo modprobe erofs f2fs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo -n "${{ secrets.PLATFORM_KEY_PK8 }}" | base64 --decode > security/unica_platform.pk8
          echo -n "${{ secrets.PLATFORM_KEY_PEM }}" | base64 --decode > security/unica_platform.x509.pem

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Build dependencies
        run: |
          source ./buildenv.sh a52sxq
          ./scripts/build_dependencies.sh

      - name: Update prebuilt blobs
        run: |
          source ./buildenv.sh a52sxq
          ./scripts/internal/update_prebuilt_blobs.sh ${{ matrix.path }}
          echo "PDA_BUILD=$(cat ./${{ matrix.path }}/.current | cut -d "/" -f 1)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            ${{ matrix.path }}
          commit-message: '${{ matrix.path }}: update blobs to ${{ env.PDA_BUILD }}'
          committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          branch: '${{ matrix.path }}'
          delete-branch: true
          title: 'Update ${{ matrix.path }} blobs to ${{ env.PDA_BUILD }}'
          body: ''
